### ISSUE TITLE
Tool won't process lidar

### ISSUE THREAD

**Issue by MyronBedford** [chadrockey/TGC-Designer-Tools#107]
I have selected the course directory and imported the course but when I'm processing lidar it runs for 10 seconds then comes up with this error,

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 521, in runLidar
  File "lidar_map_api.py", line 345, in generate_lidar_previews
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by pobee10** [comment]
Having same issue - cant process any Lidar - any ideas?

**Comment by MyronBedford** [comment]
The weird part is that it worked literally the day before. I have made multiple attempts but have messed up at other places so I've had to restart but suddenly it just stopped processing

**Comment by pobee10** [comment]
I am at a loss - the error is referencing back to the python code

**Comment by chadrockey** [comment]
There’s an issue with Mapquest potentially when trying to get the satellite data, so you know your EPSG is correct.  If it’s not fixed by the end of this week, I may release a new version to handle Mapquest being down.  Let’s hang tight.

**Comment by pobee10** [comment]
You're the man.  open.mapquestapi.com seems unresponsive so hopefully a server side error

**Comment by MyronBedford** [comment]
Does that mean that I have to install a new version of the tool or will it update the old one?

**Comment by upsdsp** [comment]
Any update?  Still getting the same error.  Thanks for your time.

**Comment by chadrockey** [comment]
MapQuest API appears to be very much broken:
https://twitter.com/mysterywisc/status/1587519231188410370?s=20&t=eBNwyb8APj1r-GEY6yQG-w

https://twitter.com/LrakWortep/status/1587458337691832320?s=20&t=eBNwyb8APj1r-GEY6yQG-w

https://twitter.com/nopanen/status/1588214935967834115?s=20&t=eBNwyb8APj1r-GEY6yQG-w

I'll think about what to do, but without the MapQuest feature EPSG verification is extremely difficult.

**Comment by upsdsp** [comment]
Bummer.  Wish I knew more to offer help.

**Comment by pobee10** [comment]
Is Mapquest the only service that can accomplish?  Googles API won’t work
or bing?

**Comment by pobee10** [comment]
Chad - totally willing to compensate/donate to get this back up and running
if possible.  Such a great tool.  Wondering if google could replace based
on the below?

https://developers.google.com/maps/documentation/geocoding/overview

**Comment by Hiblet** [comment]
I would chuck into a donation pot too.  I have made about 40 courses for PGA2k21 with this awesome tool, and I am now completely poked.  Thanks Chad!

**Comment by Hiblet** [comment]
Update:  I got an image back on the left showing Lidar, but nothing on the right, ie no mapquest image.  I got an error in the front end (ie not DOS box) saying "Could not get sat preview: HTTP Error 403: Forbidden"

**Comment by MyronBedford** [comment]
I'm making a lidar for TGC 2019 and I'm coming up with the same error, I'll see if it works though.

**Comment by pobee10** [comment]
If you know you have the right EPSG, if you draw the box around the left
side LiDar - will it still process?

**Comment by Hiblet** [comment]
Yes, I have done a run.  Once you have selected an area of data in the Accept screen, business as usual.

**Comment by MyronBedford** [comment]
Yes it will process lidar. I'm having a problem where when it loads the course preview it doesn't show any holes. just the trees.

**Comment by pobee10** [comment]
That may be due to busy servers at OSM.  Have to run the tool in evenings
(eastern time) or weekends

**Comment by pobee10** [comment]
I actually just did one from scratch and it worked with elevation looking
good.  It was from Lidar in which the EPSG was in the file and no override
was needed in the tool.

**Comment by chadrockey** [comment]
@MyronBedford EPSG is likely wrong.  The reason this was such an important feature was to confirm that the EPSG is using the right units and course is in the right place.  OSM not showing up because the EPSG is wrong.

I’m still looking into solutions, but instead of returning garbage data, they return 403 finally, a real error code.

**Comment by MyronBedford** [comment]
The thing is though  is that when I receive the screen to select the area for my course there's this black square exactly where the elevation started going crazy. I have seen this even at my first attempt before mapquest shut down.

**Comment by MyronBedford** [comment]
And part of the course is just fine and has the proper elevation.

**Comment by chadrockey** [comment]
@MyronBedford Can you open a new issue where you list the files used by your course?  It seems as if there may be mixed files from different years or sources/a missing one.

**Comment by goffst** [comment]
Hello,
I'm trying to do my first course and I'm not very successful yet. Should I wait until this issue is resolved?

Not sure I've even got the right epsg. I think it is 2236 for East Florida.

Thanks

**Comment by goffst** [comment]
I tried using the epsg with the 403 error from mapquest. It makes all the files and I exported the course file.  Once I load up the TGC simulator and edit the course, I can see the course, all the holes, greens and sandtraps. However, I can play any holes. It looks like the terrain loaded but it doesn't have any holes. Any suggestions?

**Comment by goffst** [comment]
I finally got it to work. I wasn't tagging the hole correctly.

The only thing that doesn't show up is the water around the holes

**Comment by Hiblet** [comment]
@goffst Check your OSM tag for the water feature.  Only "golf" tags are pulled, so you would need golf:lateral_water_hazard set on the feature.  I have seen some lakes with inner/outer lines, and these don't come in.  

Don't stress it too much, if the water does not come in you can still use the height of the land to figure out how the water sits.  Make a large water pane, lower it till it just breaches the land where you expect it to be, and it should be close the right shape.

**Comment by goffst** [comment]
thanks for your help. Got the water hazards. Is there any reason why I only have red tees? I made all the tees and the tags seem right.

**Comment by MyronBedford** [comment]
I'm pretty sure that when you make a course in TGC 2019 you only get given one set of teeboxes. Just go into the teebox you have and click add teebox and you'll get another set of teeboxes. From there just move them to where the teebox should be.

**Comment by chadrockey** [comment]
Fix with released mapquest version released:
https://github.com/chadrockey/TGC-Designer-Tools/releases/tag/v0.3.3
