### ISSUE TITLE
Could not load USGS_LPC_FL_Peninsular_2018_D18_LID2019_256287_E.laz Please report this issue

### ISSUE THREAD

**Issue by goffst** [chadrockey/TGC-Designer-Tools#109]
Hello,
Trying to process my local course. At first I did not include enough of the lidar area to include everything in the square to choose. I got a memory error. Then I included the area to fill the square (not part of the course but needed to fill the area)
After that I kept getting the above error on the last lidar file. It worked before. I have tried many times and same error.

Here is the complete error message:
Proj4 : pyproj.Proj('+units=m +init=epsg:2236 ', preserve_units=True)
Processing: USGS_LPC_FL_Peninsular_2018_D18_LID2019_256287_E.laz
Overwriting projection with EPSG:2236
Unit in use is 0.3048006096012244
Proj4 : pyproj.Proj('+units=m +init=epsg:2236 ', preserve_units=True)
Could not load USGS_LPC_FL_Peninsular_2018_D18_LID2019_256287_E.laz Please report this issue.
Generating lidar intensity image

also included is the area map I am referring:

![Screenshot 2022-11-17 204015](https://user-images.githubusercontent.com/117947446/202591791-91209dad-86d9-49a7-bf65-0bd92c96935e.png)

Let me know if you need more information or tell me what I'm doing wrong.
Thanks

**Comment by chadrockey** [comment]
Try downloading a fresh copy of that file, it may not be a complete download

**Comment by goffst** [comment]
I've already tried that, but will do it again. 
Thanks

**Comment by goffst** [comment]
Ok,  I have a total of 6 lidar files. The 5th file does not include any golf course data. If I exclude this file, the above lidar file does get processed.  However I do believe I need this file because I can't draw a box around the area without this file (if I'm making sense - there is a black box that will be included if I draw the box to process)

Not sure what to do next

**Comment by goffst** [comment]
I have  tried again with only the lidar file that did not work as mentioned above (256287). It worked with only that lidar file. Then I tried with the other five lidar files and the single file that did work, now doesn't work with the other five. The other five did work.

**Comment by goffst** [comment]
Please close this issue. I ran the tool on another computer and it worked fine. No explanation on why the first did not work (that computer is I7 with lots of memory)
