### ISSUE TITLE
Error Code: HB-RS[1702] unknown network error

### ISSUE THREAD

**Issue by grant2145** [chadrockey/TGC-Designer-Tools#11]
After exporting the course file and moving it to the courses folder within TGC 2019 I'm unable to open the course within the game.  I get the error code HB-RS [1702]  

Is there something I'm doing wrong?  Thanks

**Comment by chadrockey** [comment]
@grant2145 sorry I didn't have notifications on for this repo.

When that happens, it means the course is corrupt for some reason.

The most common reason I see if copying a course before it's been fully saved.  Be sure to wait until the preview image shows again after you click export before trying to load the course.

Also double check your OSM to make sure that there aren't any weird characters or invalid pars, like no par 40 holes.
