### ISSUE TITLE
Could not get sat preview: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sgpeterson23** [chadrockey/TGC-Designer-Tools#115]
I'm getting this error message. Could not get sat preview: HTTP Error 403: Forbidden
Any help is appreciated!
![Capture2](https://user-images.githubusercontent.com/121255699/209204286-27862e34-4d1e-42d4-a45b-b91e67f8d500.JPG)

**Comment by Bry-Da-Man** [comment]
I also received this error, but the LIDAR data did appear and I was able to select the course and click Accept to move on.  Another window pops up - is it hidden from you?

**Comment by chadrockey** [comment]
Mapquest's API broke a while back and I haven't found a good alternative yet.  I'm hesitant to have people copy past links into their browser to see Google data.

**Comment by Bry-Da-Man** [comment]
Is it an issue?  Or is that just for a Mapquest reference when selecting the course.  Only the black/white layout shows,

**Comment by chadrockey** [comment]
Yes. The black and white is the raw LIDAR data, it will always look correct.  Without the satellite image, there will be many more EPSG issues where tracings can’t appear on the course because the EPSG is wrong and can’t be confirmed.

**Comment by kaptinenny14** [comment]
I got in touch with Mapquest. Here's their reply:

Hi Ken, 
The MapQuest team does not support the TGC2019 game. 
With that in mind, when you contact the TGC2019 team, let them know that the [open.mapquestapi.com](http://open.mapquestapi.com/) APIs were all sunset in October 2022. 
Have a great day.
Brian
Brian Coakley
API Integration Engineer
o: 844-243-1028 | e: [support@mapquest.com](mailto:support@mapquest.com)

**Comment by chadrockey** [comment]
Release with fixed mapquest:
https://github.com/chadrockey/TGC-Designer-Tools/releases/tag/v0.3.3

**Comment by kaptinenny14** [comment]
Thank you!
