### ISSUE TITLE
SSL cert expired in tool

### ISSUE THREAD

**Issue by danielrjermyn** [chadrockey/TGC-Designer-Tools#120]
Looks like the SSL cert that links to OSM has expired for this. I'll pay $$$ if someone can regenerate the cert and  update the tool. As of now, it looks like the tool is officially unusable
![certExpired](https://user-images.githubusercontent.com/97063199/226925640-7cc9f161-f849-464a-b604-6175eaf67453.png)
 until this is updated.

**Comment by DoubleBird1** [comment]
I experienced the same issue. However, I think it is related to open.mapquestapi.com request for image. Hope this helps. Also, would like to see if this issue can get fixed.
![SSL Error - Last Tool Event](https://user-images.githubusercontent.com/128757445/227387467-5c317bb2-da8e-4d0d-b97e-7662b304028c.png)

**Comment by AlphaIce370** [comment]
I created an account to state that the mapquest api certificate expired on March 21st. I submitted a ticket with them, using my specific open.\mapquestapi.com that had expired. Hopefully they will update their certificate and this will resolve the issue.

**Comment by AlphaIce370** [comment]
I received a response from support earlier today. I passed on my certificate error and some screenshots/links to assist them with.

**Comment by AlphaIce370** [comment]
@chadrockey 
I heard back from the devs about the certificate issue. I hope this is of assistance to you.

Brian Coakley (MapQuest B2B Support)

Mar 28, 2023, 7:07 PM MDT


The development team rolled out updates to our full suite of APIs and mapping tools in September 2022. MapQuest is getting ready to help developers build bigger, better, and more global apps. Part of that process was deprecating some of our older and less utilized services to streamline our platform for substantial refinements.
 
The following services have reached their end of life:
The open geocode, directions, guidance, mapping, elevation, and Nominatim APIs
The Directions API Path from Route and Find LinkID functions
The Static Map v5 "@2x" parameter
The unofficial/beta Geocode API v2
All Traffic API v1 and Directions API v1 will reach the end of their lives and all requests should be updated to v2
Static Map v4
All native mobile SDKs (mapping and navigation)
The MapQuest JavaScript v7, Leaflet plugins v1, and Flash SDKs that were sunset in 2016-2018 will stop displaying map tiles
 
The Open Geocode v1, Directions v2, and Static Map v5 APIs can be replaced by their licensed counterparts by replacing the [open.mapquestapi.com] (http://open.mapquestapi.com/) base URL with [www.mapquestapi.com](http://www.mapquestapi.com/) with little or no code update.

**Comment by AlphaIce370** [comment]
You bet, keep me posted if I can help out at all. Hopefully it is just an easy swap of the python scripts. Who knows, they were very responsive to me when submitting to support@mapquest.com

**Comment by AlphaIce370** [comment]
Hey @chadrockey,
Is it as easy as swapping the lidar_map_api.py #329 and some other similar lines for this link [www.mapquestapi.com](http://www.mapquestapi.com/)? I'm guessing you'll have to do some back end work within Mapquest for it to handle it (I don't deal with API's much, but I'm decent with some code).

**Comment by weldonetig** [comment]
Signed up today,It's weird the course i wanted to work on had this SSL error. Just splined another course on OSM and ran TGC version 0.3.5 and course came right into the tool. But still cannot get the course i wanted to do. So i thought maybe the issue had been fixed. Tried the version 0.3.5 and lidar shows but will not pull course from OSM on any ESPG code that i tried.

**Comment by jakehmccoy** [comment]
I am getting valid responses from the www.mapquestapi.com endpoint.

**Comment by chadrockey** [comment]
This ticket is getting confused with an OpenStreetMap expired server configuration and MapQuest (a commercial site similar to Google Maps) having a horrible migration and closing their APIs.

For now, my MapQuest developer account is still very broken.

<img width="880" alt="Screen Shot 2023-03-31 at 1 49 26 PM" src="https://user-images.githubusercontent.com/230240/229204974-cda4b3ab-096d-46c1-9a4b-7bcf051fdf37.png">

**Comment by jakehmccoy** [comment]
@chadrockey I am trying to fix on a local branch by using my own MapQuest API key and changing the open.mapquestapi.com/staticmap/v5 endpoint to www.mapquestapi.com/staticmap/v5.  I'm getting valid responses that I can build into images from this new endpoint, but I'm having pip issues installing your version of laspy.

**Comment by AlphaIce370** [comment]
Do you need to reach out to support about your account Chad? I'm wondering if there was a plan change and you're on something that was grandfathered? Given all the other changes/API stuff that has been deprecated it could be the issue. I just created a new one and didn't have any issues FWIW.

**Comment by danielrjermyn** [comment]
Pretty sure the communities on the FB groups would happily set up a GoFundMe if that was a barrier to get the issue resolved.

**Comment by jakehmccoy** [comment]
> Pretty sure the communities on the FB groups would happily set up a GoFundMe if that was a barrier to get the issue resolved.

It isn't.  I have a PR in that will fix this issue if the MapQuest API key is refreshed.

**Comment by duff259** [comment]
Would love to do anything to help the process here. @chadrockey I am having the same issue described above. Anybody have a workaround solution?

**Comment by Baconjunkie1** [comment]
> Would love to do anything to help the process here. @chadrockey I am having the same issue described above. Anybody have a workaround solution?

Download the newer version .... tgc_gui_0.3.5.exe

https://github.com/MTBehnke/TGC-Designer-Tools/releases/tag/v0.3.5?fbclid=IwAR0asKvYX1fF-aOor_hvYqFiMAYmm6CWYywvdh84nSJcBijrgMH3Vprk68g

**Comment by jakehmccoy** [comment]
@Baconjunkie1 in the lidar_api file in your fork, the mapquest api call is still to open.mapquestapi.com.  Needs to be www.mapquestapi.com, no?

**Comment by chadrockey** [comment]
@jakehmccoy my account and API keys are invalidated, the code fix may be simple but I need my account reinstated.

**Comment by AlphaIce370** [comment]
Any luck with your account being reinstated?

**Comment by gelsingerj** [comment]
> @jakehmccoy my account and API keys are invalidated, the code fix may be simple but I need my account reinstated.

Anything we can do to assist @chadrockey

**Comment by chadrockey** [comment]
The developers had to edit my account in the database.  I should have restored access and will be releasing a fixed version this weekend.

**Comment by gelsingerj** [comment]
> The developers had to edit my account in the database. I should have restored access and will be releasing a fixed version this weekend.

Where can I venmo you some money?  I design courses to help with my PTSD and my favorite to do is RCR via Lidar. I really appreciate all that you have done.

**Comment by gelsingerj** [comment]
I posted a reply on the site, but if you have a Venmo account I would like to send you a little something to say thanks. Your tool brings me a lot of joy. I am a disabled veteran and use the course designer as a source of therapy. Using LiDAR to do RCR courses are my favorite part. I bought a PC just to do that. So thanks again.

John Gelsinger
Vice President
Business Development &
System Integrators
512.713.4042 (m)
***@***.***
**sent from my mobile command center**


________________________________

**Comment by gelsingerj** [comment]
@chadrockey is there going to be a new version we have to download or is the old one going to start working? I am excited to get back to building more courses for the community. Standing By... thanks.

**Comment by falk-herrmann** [comment]
> @chadrockey is there going to be a new version we have to download or is the old one going to start working? I am excited to get back to building more courses for the community. Standing By... thanks.

Hope, Chad is still active and committed to the project. If you want you can use my build with Mapquest URL fix 
[https://github.com/falk-herrmann/TGC-Designer-Tools](https://github.com/falk-herrmann/TGC-Designer-Tools). No further changes.

**Comment by odcheck** [comment]
@falk-herrmann It works like charm. Thank you very much.

**Comment by KahDon** [comment]
@falk-herrmann @odcheck I am a newbie. Was trying to build my home course this weekend. How do I switch that lidar_map_api.py file? I have the original .exe file but unsure what to do from there. I downloaded the source code from here and swapped the .py file but not sure how to make that reflect on the .exe file. I know this is an extremely dumb question to most lol

**Comment by weldonetig** [comment]
@falk-herrmann, I downloaded the updated tool and I tried every EPSG in Colorado. It shows correct area but still does not pull in OSM features only a gray picture. Lidar is fine but no golf course features. And also a special thanks to all that are trying to get this working again.

**Comment by KahDon** [comment]
> @falk-herrmann @odcheck I am a newbie. Was trying to build my home course this weekend. How do I switch that lidar_map_api.py file? I have the original .exe file but unsure what to do from there. I downloaded the source code from here and swapped the .py file but not sure how to make that reflect on the .exe file. I know this is an extremely dumb question to most lol

never mind, I'm an idiot haha

**Comment by chadrockey** [comment]
New release for Mapquest issue, OSM certificate also resolved.

https://github.com/chadrockey/TGC-Designer-Tools/releases/tag/v0.3.3
