### ISSUE TITLE
Two side by side courses causing problems

### ISSUE THREAD

**Issue by Blixt99** [chadrockey/TGC-Designer-Tools#127]
Hello Chad, 

I love your tool but I’m having a problem because my home course property consists

of two side by side courses  I noticed on your GitHub page that back in 2019 you added a feature that addresses this issue.

To quote your note from there---"You can now export the holes on a course into a separate file and reinsert them later.

This helps with courses that may have 27 hole routing or two courses on the same plot. Now you can fix and polish

just one course, and go back and forth between the two layouts.” 

I’ve had all kinds of trouble trying to get each course separately into TGC 2019 course designer and I’ve run into nothing
 
but problems. 

I see the buttons that I guess facilitate this feature but I don’t know how to use them. If you could explain how they are used for me I would greatly appreciate it. Thanx a ton.

**Comment by chadrockey** [comment]
Hi, there’s a text field somewhere for you to filter features based on the name you can enter in OSM when you create the routing there.

So for instance I had Angel Park Palm Hole 1 and Angel Park Mountain Hole 1.

By entering 

Palm

into filter holes, it only imports holes that have Palm anywhere in the name.

**Comment by Blixt99** [comment]
I think I know what you're saying, I'm not absolutely sure. I went back to OSM and added a Tag  with a key and a value for each hole on each course.                             Key               Value                    Key                Value
For instance:    Greenback #14 - hole     and     Great Blue #14 - hole
Is this what you meant?
You lost me with "filter holes".  There's no button on the Course Tools tab in TGC Golf Tools named "filter holes"Where would I enter, as you say    Palm    into filter holes?
Could you lay out step by the process I would use in doing this. Your tutorials don't cover this feature so I'm kinda lost..
I really appreciate all the work you've put into this app. and so far it's thrilling to try and recreate the coursesI played for decades. Thanx a lot.    On Sunday, June 25, 2023 at 01:58:45 PM PDT, Chad Rockey ***@***.***> wrote:  
 
 


Hi, there’s a text field somewhere for you to filter features based on the name you can enter in OSM when you create the routing there.

So for instance I had Angel Park Palm Hole 1 and Angel Park Mountain Hole 1.

By entering

Palm

into filter holes, it only imports holes that have Palm anywhere in the name.

**Comment by Blixt99** [comment]
Chad, here's my follow up. I went and looked at your Fields and Tags for the golf holes you did at Angel Park Palm and Mountain courses.
I then did the same for all my golf holes on the Greenback and Great Blue courses I'm working on (see attached pic).
I'm still confused by your, "By entering Palm into filter holes, it only imports holes that have Palm in the name."      How do I accomplish this? 

Hope you can help me understand. Thanks.






    On Sunday, June 25, 2023 at 05:51:12 PM PDT, steve blixt ***@***.***> wrote:  
 
  I think I know what you're saying, I'm not absolutely sure. I went back to OSM and added a Tag  with a key and a value for each hole on each course.                             Key               Value                    Key                Value
For instance:    Greenback #14 - hole     and     Great Blue #14 - hole
Is this what you meant?
You lost me with "filter holes".  There's no button on the Course Tools tab in TGC Golf Tools named "filter holes"Where would I enter, as you say    Palm    into filter holes?
Could you lay out step by the process I would use in doing this. Your tutorials don't cover this feature so I'm kinda lost..
I really appreciate all the work you've put into this app. and so far it's thrilling to try and recreate the coursesI played for decades. Thanx a lot.    On Sunday, June 25, 2023 at 01:58:45 PM PDT, Chad Rockey ***@***.***> wrote:  
 
 


Hi, there’s a text field somewhere for you to filter features based on the name you can enter in OSM when you create the routing there.

So for instance I had Angel Park Palm Hole 1 and Angel Park Mountain Hole 1.

By entering

Palm

into filter holes, it only imports holes that have Palm anywhere in the name.

**Comment by Blixt99** [comment]
Okay Chad, I've added another $40 on top of the initial $10 I sent to you. Hopefully this will be enough incentive foryou to provide me with step by step instructions, or maybe a video, explaining the procedure for separating the two courses.
Thanks for your help.                       .


    On Monday, June 26, 2023 at 01:01:06 AM PDT, steve blixt ***@***.***> wrote:  
 
  Chad, here's my follow up. I went and looked at your Fields and Tags for the golf holes you did at Angel Park Palm and Mountain courses.
I then did the same for all my golf holes on the Greenback and Great Blue courses I'm working on (see attached pic).
I'm still confused by your, "By entering Palm into filter holes, it only imports holes that have Palm in the name."      How do I accomplish this? 

Hope you can help me understand. Thanks.






    On Sunday, June 25, 2023 at 05:51:12 PM PDT, steve blixt ***@***.***> wrote:  
 
  I think I know what you're saying, I'm not absolutely sure. I went back to OSM and added a Tag  with a key and a value for each hole on each course.                             Key               Value                    Key                Value
For instance:    Greenback #14 - hole     and     Great Blue #14 - hole
Is this what you meant?
You lost me with "filter holes".  There's no button on the Course Tools tab in TGC Golf Tools named "filter holes"Where would I enter, as you say    Palm    into filter holes?
Could you lay out step by the process I would use in doing this. Your tutorials don't cover this feature so I'm kinda lost..
I really appreciate all the work you've put into this app. and so far it's thrilling to try and recreate the coursesI played for decades. Thanx a lot.    On Sunday, June 25, 2023 at 01:58:45 PM PDT, Chad Rockey ***@***.***> wrote:  
 
 


Hi, there’s a text field somewhere for you to filter features based on the name you can enter in OSM when you create the routing there.

So for instance I had Angel Park Palm Hole 1 and Angel Park Mountain Hole 1.

By entering

Palm

into filter holes, it only imports holes that have Palm anywhere in the name.

**Comment by chadrockey** [comment]
@Blixt99 Sorry I dropped this!  Do you still need a guide on this feature?

**Comment by Blixt99** [comment]
Hey Chad,
Actually I do.  I have no problem matching hole names for each course when I Import Terrain and Features. After that I have no idea how to separate the terrain and holes fromone course and then combine them into one distinct course using the buttons in the Course Tools section. Some guidance on this issue would be greatly appreciated. Thanx.
    On Friday, July 14, 2023 at 12:01:17 AM PDT, Chad Rockey ***@***.***> wrote:  
 
 


@Blixt99 Sorry I dropped this! Do you still need a guide on this feature?
