### ISSUE TITLE
Prj2EPSG.org not loading

### ISSUE THREAD

**Issue by Joseph-Leonard** [chadrockey/TGC-Designer-Tools#15]
getting "Problem looking up epsg with prj2epsg.org, try tool later." message when importing .laz file

**Comment by chadrockey** [comment]
@Joseph-Leonard hi, sorry about this, notifications were off on this repo.

Occasionally pr2jespg.org won't respond to requests.  When you can go to http://pr2epsg.org in your browser, then everything should work again.
