### ISSUE TITLE
Could not determine lidar projection...

### ISSUE THREAD

**Issue by gkleinfe** [chadrockey/TGC-Designer-Tools#16]
I followed the tutorial at https://chadrockey.github.io/TGC-Designer-Tools/TUTORIAL earlier today at work with no issues.  I downloaded the lidar (.laz) files and the corresponding metadata (.xml) file and you application was able to process and generate the height maps.

Now that I'm home, I'm trying to start from scratch using the exact same file from work and I got the error that it could not determine lidar project.  The same EPSG error as mentioned in http://tgctours.proboards.com/thread/18202/help-asking-me-epsg-code.  I'll request the EPSG, but I find it odd that it worked at work today, but not at home with the same files.

Here's a link to the lidar files.
https://1drv.ms/u/s!ArcKzQRs3GBUgYNmhvjsDlt_RxCvTA?e=O2PV7R

Any help is appreciated.  I was having a blast setting this up.

Course : Riverby Hills Golf Club
Address : 16571 W River Rd, Bowling Green, OH 43402

**Comment by chadrockey** [comment]
I don't support users on Github.  This is more or less for the internal workings of the tool and/or crashes/glitches/bug fixes.

Please ask here if you haven't already:
http://tgctours.proboards.com/board/98/lidar-help
