### ISSUE TITLE
Course extends beyond .course file

### ISSUE THREAD

**Issue by rprochnow** [chadrockey/TGC-Designer-Tools#18]
The course I'm trying to create from LIDAR/OSM is too long in one direction to fit on top of the blank .course file, leaving part of the "top" and "bottom" of the course outside of the editable area of the .course file.

It appears the designer tool is loading the LIDAR-generated trees in the correct location and height - but they extend outside of the editable .course area.

Any suggestions???

**Comment by rprochnow** [comment]
I was able to just barely squeeze the course into the .course file by doing a rotate and move.

A better solution would be to resize the .course file to fit LIDAR/OSM data, if that's even possible...

**Comment by rprochnow** [comment]
According to the source code, the auto rotation is limited to 45 degrees in either direction.

To get the course to fit manually, I apply a 64 degree rotation and then a -50 east/west shift.

And even then, this cuts off some of the trees that are located around the farthest extremes of the course.

**Comment by chadrockey** [comment]
@rprochnow You need to add the line type golf->holes on OpenStreetMap.  Then the game will automatically expand the plot.  The game doesn't officially support more than 2000m x 2000m but this workaround has been there forever.

We don't draw it in the preview, but it will render fine in the game.

**Comment by rprochnow** [comment]
What object should that be on?

Thanks!

**Comment by rprochnow** [comment]
Chad,

First, your tool was a great help in merging the terrain and course layout together for import into TGC 2019.

We’re members of Barton Creek Country Club in Austin, TX, and I’m in the process of loading all 4 of their courses.

The course I’m having problems with is the Fazio Foothills course – which is laid out in an area that just barely fits within the standard 2000x2000 layout, and only by manually rotating and shifting the course to get all of the greens and tees to just barely fit.

I’m looking at one of the holes that is barely on the edge – hole 14.  There is a “golf hole” defined for that hole, with a golf=hole tag.

This has been done for all 18 holes on this course – and for the other 3 courses.

If “golf: holes” is needed, what object is that tag placed on?

Thanks!


Bob Prochnow
Executive Director, Technology Collaboration Center - techcollaboration.center<https://techcollaboration.center/>
281-969-7801 (office)
Bob.Prochnow@TechCollaboration.center<mailto:Bob.Prochnow@TechCollaboration.center>
[cid:image001.png@01D560DA.74D5E6D0]

**Comment by chadrockey** [comment]
@rprochnow I'm not sure someone has attempted to do such a dense golf area before, but I tried to plan ahead for this situation so let me know if it works.  If it doesn't I'll try to fix it for you.

So the game DOES allow expanding, but only when holes are next to the border - then it expands the plot by some amount to give the hole space between it and the edge.  We don't know if it's supposed to happen but it does.  You can do this manually by defining a "hole" in TGC (where you place a pin, then place a waypoint, then place a green).  Then you can select it in game and move the entire hole into or outside of a border and watch it expand.

For your use case, you do need all of the holes for your course to be imported by the tool.

The first way this is done for most courses is simply by the lidar specifying a point on the planet and all of the holes nearby are imported.  This works for 99% of users.

The next way is if there are two (or more) courses that overlap or courses where there are three nines.

I added the "Match Hole Names" filter option into the OSM pane.  For your case, are you entering "Foothills" into this field?  TGC only supports 0 to 18 holes and no more, so if there's no filter, only the first 18 are used.  If you have overlap, it might be pulling in holes from another course.  Maybe do a test play to see what happens to see if you have 16 holes or a few holes from different courses mixed in to get a weird order.

If a few are missing, double check that the hole names have exactly the same spelling with no typos and that there aren't accidents like duplicate holes, etc.

If this doesn't work, then the first thing to check is that you have lidar for the 14th hole and/or didn't accidentally mask part of it.  If part of an OSM feature isn't entirely contained within the original mask boundaries, then we don't import it - so it's worth double checking by uploading the mask file here.

Let me know how it goes.

**Comment by rprochnow** [comment]
I’ve placed labels on each of the golf holes – Foothills for the course I had problems with and Cliffside for the other course.  The Cliffside course is relatively dense and easily fits.  The Foothills course is much more spread out with two loops on either end of the course with homes in the middle, which causes the course to extend to the edge of a 2000x2000 grid.

Your tool isn’t able to automatically fit the course – the automatic rotation and shifting still cuts off portions of holes at either end of the course.

Fortunately, I am able to manually rotate and shift the course to get the greens/tees at either end to just barely fit.

But an interesting side effect is that your tool is sending over trees that fit outside of the 2000x2000 grid – they show up on the course in TGC, but those trees are uneditable.

We seem to have two issues.

First, your tool isn’t able to calculate the rotation and shifting to get the course to fit inside the square.

Second, when the holes go outside of the square, either your tool or TGC doesn’t recognize this – and a portion of those holes are cut off.

I’ve been able to workaround this with manual rotation & shift – and I’m not having these issues with the other 3 courses.

So I’m past this as an obstacle.  The biggest challenge I’m having is with TGC’s data limit – even by cutting back on trees, I’m nearly at 100%.

Overall, your tool works well – though I wish there was some “mouse over” help on the various options on each screen.

Thanks for the feedback!

Bob

**Comment by chadrockey** [comment]
You shouldn't need to try the auto rotate or manual rotate - the course INSIDE OF TGC should expand.  The preview INSIDE THE TOOL will not expand.  This is just an oversight/lack of time/bigger priority issue.

If the holes are present, then the course inside of TGC will expand to allow most to be editable.

The autorotation feature was from before we knew if the IN GAME course expansion was reliable and it turned out it was, so I disabled autorotate by default.  It now leaves in game north as course north same as real life north.  This is important for a lot of users who are picky about the sun.

As a side note, the 45 degree limitation is because the plot is a square, so the most ANY rotation could fix the plot would be 45 degrees to try to line up the long edge along the diagonal of the square.

----------------

Yes, going outside the bounds can happen but there's nothing I can do for that.

-----------------

My recommendations would be to do another import, don't touch the rotations at all, and see how the course looks in game.  You probably want North to align.

Then you'll need to mask out anything that isn't directly playable with red in the mask to reduce the course file usage.  You'll have to paint around each and every hole and get rid of the houses, the creek, the clubhouse, the driving range, and everything.  Since they aren't part of a playable hole, they don't really show up in game ever and with such a large course you don't have the luxury of including them or their trees.  You can do some rough sculpting and do auto plant trees or batch plant trees in those areas to blend them in.  If you mask out everything but playable area, you should only use 30-50% of the resource meter.

**Comment by rprochnow** [comment]
Chad,

Finally got a block of time to revisit this…

I re-ran the .course generation in the designer tool.  “Auto Position & Rotate” was not selected on Import Terrain.  And I didn’t select any options on the Course Tools windows when exporting the course – and TGC 2019 is now showing the entire course.

I’ve already finished this course using the manually rotated and shifted version – and will take the new .course file and re-apply all of my edits in TGC, which should work better, since the holes along the edge will now have more spacing around them.

Thanks!

Bob

**Comment by chadrockey** [comment]
Glad it worked for you, I might remove that option since it doesn’t appear to be needed and in your case was a trap for technical and forward thinking users.

I have to keep manual shifts and rotates for courses along a coast, but the auto doesn’t really serve a purpose now.

**Comment by rprochnow** [comment]
An informational message below the preview window may also be helpful – noting that the preview window may not contain all of the data that will be included in the .course export.

Thanks!

Bob
