### ISSUE TITLE
Tool gives prj2epsg.org error

### ISSUE THREAD

**Issue by jayrodathome** [chadrockey/TGC-Designer-Tools#19]
Repeatedly get error that says problem looking up epsg with prj2epsg.org. Looking into it further epsg.org put out a statement saying they were updating their data set this month and users would need to register again to use the service. Not sure if that's related but just figured I'd post it. Here's a link to the article. https://www.iogp.org/blog/epsg/upgrade-of-epsg-dataset-data-model/

TYVM! 
![image](https://user-images.githubusercontent.com/6989388/66284354-5a0bba80-e895-11e9-9d21-d89b511a614f.png)

**Comment by jayrodathome** [comment]
I just noticed a recently closed issue related to this same error. I will try again tomorrow see if it's working again. TY

**Comment by chadrockey** [comment]
Their service and free and amazing, unfortunately, it's not always available.  Trying again later is the best you can do.
