### ISSUE TITLE
lidar generation bad

### ISSUE THREAD

**Issue by nbargolf** [chadrockey/TGC-Designer-Tools#24]
This is what it looks like
https://user-images.githubusercontent.com/58559531/71589851-5b472f00-2af4-11ea-81ea-b2a205664b25.png. I must have done something wrong but this is the second area I have done that looks like this.

**Comment by NobleComputing** [comment]
You have the wrong epsg number for the lidar.

**Comment by NobleComputing** [comment]
or the LiDAR data is too old to use.  Anything older than 2008 is a fail.

**Comment by chadrockey** [comment]
This is the wrong EPSG, it will probably look fine in game once the sat map matches.

The stripes are because the airplane has overlapping observations for each flight.

**Comment by NobleComputing** [comment]
Like Chad said, if the picture on the right does not show the golf course, it is the wrong epsg number.
