### ISSUE TITLE
mask.png file is not being generated

### ISSUE THREAD

**Issue by z3nz** [chadrockey/TGC-Designer-Tools#25]
Followed all the steps in the tutorial here: https://chadrockey.github.io/TGC-Designer-Tools/TUTORIAL

Got to the step where it is actually processing the lidar data and it generates the `heightmap.npy` file successfully, but it does not create a `mask.png` file in the same directory.

![image](https://user-images.githubusercontent.com/11219533/72753869-1f076b80-3b94-11ea-94fe-7868c71bcd93.png)

![image](https://user-images.githubusercontent.com/11219533/72753887-29c20080-3b94-11ea-887e-3a1499aa7f3e.png)

![image](https://user-images.githubusercontent.com/11219533/72753900-347c9580-3b94-11ea-9b24-11b6f7f85572.png)

Tried running it again and got the same result.

Thanks in advance.

**Comment by NobleComputing** [comment]
You are trying to save in the wrong directory!  Why are trying to save it in the UNPACKED directory?  You cannot save it to that directory.

**Comment by patator100** [comment]
Hi Z3nZ, have you managed to fix your issue, I have the same problem - no .png file (but I have no error message in the dos window - it's just blanck)
thanks
pat

**Comment by patator100** [comment]
I found the issue, don't use any special character in the folder path, mine contains a "è"...and the whole process crashes, including when generating course from lidar and osm
