### ISSUE TITLE
Generating lidar intensity image - Exception in Tkinter callback

### ISSUE THREAD

**Issue by MJJgolfing** [chadrockey/TGC-Designer-Tools#26]
The tgc_gui_0_3_0.exe routine encounters an error when trying to process Lidar files.  Attached files should provided needed details.  Thanks!  Mike
[Lidar Processing.txt](https://github.com/chadrockey/TGC-Designer-Tools/files/4114324/Lidar.Processing.txt)
![Tkinter callback DOS screen](https://user-images.githubusercontent.com/60292364/73141567-83727100-4053-11ea-8f6b-d137dfc9de9e.jpg)

**Comment by NobleComputing** [comment]
That normally means you have two different versions of las/laz files in your files.  Make sure they are the identical set.

**Comment by chadrockey** [comment]
Either your computer doesn't have enough memory to process these files or as Nobleman mentioned, you've mixed two different collections of lidar.  All of your lidar has to be from the same year and same collection.
