### ISSUE TITLE
Updated mask doesnt return expected results

### ISSUE THREAD

**Issue by H3GGERS** [chadrockey/TGC-Designer-Tools#27]
Hey there! Just wondering why my updated masks dont seem to get taken into account in the final output? I'm using 100% Red for my masking but the final output doesnt seem to look like your examples. 

It looks like its correctly removing data but i thought it'd mask out the brown too?

Any help would be greatly appreciated! Thanks

![Annotation 2020-02-23 232526](https://user-images.githubusercontent.com/1449645/75132347-d6ac0380-5693-11ea-9e79-f5d1120e6160.png)
![Annotation 2020-02-23 232551](https://user-images.githubusercontent.com/1449645/75132348-d7449a00-5693-11ea-84cc-869a5c803f27.png)

**Comment by NobleComputing** [comment]
There is no way of getting rid of OSM splining that other people do.  It will show up and you will have delete the splines.  The brown does not count for anything as far as the resource meter in TGC 2019, so you don't have to worry about it.

**Comment by chadrockey** [comment]
The brown is "background terrain".  If you don't want that, just uncheck the box.  Background terrain uses minimal resources and will be everywhere under red so you don't have to try to sculpt it to look decent yourself.
