### ISSUE TITLE
tgc designer tool not starting!!!

### ISSUE THREAD

**Issue by Neuner-joe** [chadrockey/TGC-Designer-Tools#29]
![Screenshot (24)](https://user-images.githubusercontent.com/62057840/76508673-12461c00-644f-11ea-8f5e-f1cb29f69efb.png)
Please help me thank you

**Comment by NobleComputing** [comment]
You might want to download the latest one.  The one you have is outdated.   https://github.com/chadrockey/TGC-Designer-Tools/releases/download/v3.0.0/tgc_gui_0_3_0.exe

**Comment by chadrockey** [comment]
Maybe the file is corrupt, try downloading a new one and try again.  I've had other foreign language users, so I don't think that's the issue.
