### ISSUE TITLE
Cannot Export File

### ISSUE THREAD

**Issue by NevadaBallin** [chadrockey/TGC-Designer-Tools#30]
After editing the mask file and saving it in Paint 3D, I went to the Course Tools tab and selected Export.course but nothing shows up in the designated folder. 

Any idea why this is happening?

![OldGreenwoodExport](https://user-images.githubusercontent.com/62159711/76663235-a4c4e900-653d-11ea-91c7-c0ed6c108fd6.jpg)

**Comment by NobleComputing** [comment]
That is because you have to save the file.  There is not file to look for.   You are creating it! :)

**Comment by chadrockey** [comment]
Yes, you have to type NAMEYOUWANT.course and then click save.
