### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by SpinAxis15** [chadrockey/TGC-Designer-Tools#31]
Unfortunately having to use 6 .las files to cover a course. When I did it with one on another course everything worked fine. With 6 files I am getting the error shown in the attached file. Stops execution cold. Tried both 3.0 and 3.5
[error message.docx](https://github.com/chadrockey/TGC-Designer-Tools/files/4465201/error.message.docx)

**Comment by SpinAxis15** [comment]
merged the 6 files using LASZIP and got the following message from tgc_gui.0.3.5
"Processing: merged.las
Could not load merged.las Please report this issue.
No valid lidar files found, no action taken
Directory was: C:/Users/Steve Haines/Documents/Golf/SAMApril112020"
but the merged file was in that directory, so I am reporting this issue as requested

**Comment by SpinAxis15** [comment]
didn't mean to close it

**Comment by chadrockey** [comment]
It says memory error, so the two possibilities are: you're out of RAM (check System Monitor) or you're using two different lidar collections/files and you're trying to map a super large area by accident.
