### ISSUE TITLE
Incompatible with UK Lidar

### ISSUE THREAD

**Issue by sjmog** [chadrockey/TGC-Designer-Tools#32]
As a UK TGC player,
So I can create UK courses,
I want to process lidar exported from [Ordnance Survey OpenData](https://www.ordnancesurvey.co.uk/opendatadownload/products.html)

**Comment by NobleComputing** [comment]
That is not true sjmog.  I use it all the time to design UK customer courses.

**Comment by sjmog** [comment]
@NobleComputing that's so awesome! How do you get and/or import the Lidar or other heightmap data?

**Comment by NobleComputing** [comment]
Google is your best friend!  It is out there.

**Comment by sjmog** [comment]
@NobleComputing I spent a couple of days looking so far 😅 mind giving me a pointer?

**Comment by Loweedje** [comment]
I'm also having trouble using lidar laz files. The program keeps saying it doesn't like the file.
I made a las file of it and was able to view it in an online las viewer. The github program Displaz also doesn't like the laz file, but does open/process the las file.
This app likes neither, the las file is not ok, and it doesn't give a clue why. I tried forcing EPSG 28992, but that doesn't work/help.

**Comment by dave-tucker** [comment]
I got my UK LIDAR data from here:
https://environment.data.gov.uk/dataset/2e8d0733-4f43-48b4-9e51-631c25d1b0a9

The first link in `Available Downloadable Datasets` will let you download data LPC data in `laz` format. The second link will let you download the metadata.
I opted for GeoJSON format as it's easy to read.
The EPSG code should be in the first couple of lines.

```
"crs": {
        "type": "name",
        "properties": {
            "name": "EPSG:27700"
        }
    },
```

**Comment by paulrwebster** [comment]
You can download from https://environment.data.gov.uk/DefraDataDownload/?Mode=survey
If no Point Cloud (which is LAZ) is available, download the Composite DTM or DTM Tiles which are Geotiff Ascii. They can be converted to LAS using LASTools. I used this batch file using three utilities included with LASTools:

for %%f in (*.asc) do (
    echo %%~nf
    las2las -i %%~nf.asc -o %%~nf_A.las
    lasground -i %%~nf_A.las -o %%~nf_B.las
    lasclassify -i %%~nf_B.las -o %%~nf.las
    del %%~nf_A.las
    del %%~nf_B.las
)

**Comment by chadrockey** [comment]
Don't post support issues here.  Many UK courses have been built.

This is the support forum: https://tgctours.proboards.com/board/98/lidar-help
