### ISSUE TITLE
WARNING: Invalid body length for classification lookup, not parsing.

### ISSUE THREAD

**Issue by mattdot** [chadrockey/TGC-Designer-Tools#34]
I'm trying to use the tool to import LIDAR for Westchester Golf Course in Los Angeles.  When I "select lidar and generate heightmap" I get the following error

```
Directory was: C:/Users/matt/Documents/Westchester/lidar
Processing: USGS_LPC_CA_LosAngeles_2016_L4_6434_1805b_LAS_2018.laz
prj2epsg.org may be down, using backup for force_epsg
Could not load USGS_LPC_CA_LosAngeles_2016_L4_6434_1805b_LAS_2018.laz Please report this issue.
No valid lidar files found, no action taken
```
and the following message in the console window
```
WARNING: Invalid body length for classification lookup, not parsing.
```

These are the LAS/LAZ and metadata files I'm trying to use.  

* ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/USGS_LPC_CA_LosAngeles_2016_LAS_2018/laz/USGS_LPC_CA_LosAngeles_2016_L4_6434_1805d_LAS_2018.laz

* ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/USGS_LPC_CA_LosAngeles_2016_LAS_2018/laz/USGS_LPC_CA_LosAngeles_2016_L4_6434_1805a_LAS_2018.laz

* ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/USGS_LPC_CA_LosAngeles_2016_LAS_2018/laz/USGS_LPC_CA_LosAngeles_2016_L4_6434_1805c_LAS_2018.laz

* ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/USGS_LPC_CA_LosAngeles_2016_LAS_2018/laz/USGS_LPC_CA_LosAngeles_2016_L4_6434_1805b_LAS_2018.laz

Metadata can be downloaded from 
* https://www.sciencebase.gov/catalog/item/5b545ac3e4b05cbf87c1a440
* https://www.sciencebase.gov/catalog/item/5b545ac2e4b05cbf87c1a43a
* https://www.sciencebase.gov/catalog/item/5b545ac3e4b05cbf87c1a43e
* https://www.sciencebase.gov/catalog/item/5b545ac3e4b05cbf87c1a43c

Based on the [vendor metadata](ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/USGS_LPC_CA_LosAngeles_2016_LAS_2018/metadata/USGS_LPC_CA_LosAngeles_2016_LAS_2018.zip), I believe the correct parameters from [Spatial Reference](https://spatialreference.org/ref/esri/102645/html/) are

```
PROJCS["NAD_1983_StatePlane_California_V_FIPS_0405_Feet",
    GEOGCS["GCS_North_American_1983",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS_1980",6378137,298.257222101]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["False_Easting",6561666.666666666],
    PARAMETER["False_Northing",1640416.666666667],
    PARAMETER["Central_Meridian",-118],
    PARAMETER["Standard_Parallel_1",34.03333333333333],
    PARAMETER["Standard_Parallel_2",35.46666666666667],
    PARAMETER["Latitude_Of_Origin",33.5],
    UNIT["Foot_US",0.30480060960121924],
    AUTHORITY["EPSG","102645"]]
```

**Comment by mattdot** [comment]
So it looks like the issue is that prj2epsg.org does not have the epsg in their database.  The app is getting a 404 when trying to retrieve http://prj2epsg.org/epsg/102645.json.

Alternatively it could try spatial reference as a backup.  
https://spatialreference.org/ref/esri/102645/prj/

Tried locally and seems to work.  Will submit a PR to fix this issue.

**Comment by chadrockey** [comment]
Merged!  Thanks for the backup provider, I think users will really appreciate the tool working when prj2epsg.org is down.  Great contribution.
