### ISSUE TITLE
Support for Zlaz files

### ISSUE THREAD

**Issue by NobleComputing** [chadrockey/TGC-Designer-Tools#37]
It would be great guys if you could implement the zlaz format in to the tool.  I am running in to more of these files each day!

**Comment by NobleComputing** [comment]
I am able to convert zlas to laz files with Global Mapper

**Comment by chadrockey** [comment]
Zlas is proprietary format and I don't think we can support it.  I can't find anything that is zlaz, but it may exist.

As you mentioned, your best bet is to convert to an open standard before processing.

https://rapidlasso.com/2015/02/22/lidar-las-asprs-esri-and-the-laz-clone/
