### ISSUE TITLE
Add support for reading seperate geotiff file

### ISSUE THREAD

**Issue by Loweedje** [chadrockey/TGC-Designer-Tools#39]
Please add support for reading a separate geotiff file along with the lidar file.
The potential additional information includes map projection, coordinate systems, ellipsoids, datums, and everything else necessary to establish the exact spatial reference for the file.

https://en.wikipedia.org/wiki/GeoTIFF

**Comment by chadrockey** [comment]
GeoTiff often doesn't have enough quality or information to make great courses for users.

I've given up on adding additional file formats to automatically detect the projection since there's too many formats.  The only way to really get things right is to read the metadata and find a projection and match it to an EPSG.

**Comment by Loweedje** [comment]
Hi Chad,

I’m not sure I overlooked this, but could you point me to a list of all supported OSM objects (tags/features) that are currently supported for import ? Maybe I’ve overlook it somewhere.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chadrockey** [comment]
@Loweedje golf_type through natural_type here:

https://github.com/chadrockey/TGC-Designer-Tools/blob/master/OSMTGC.py#L428

**Comment by Loweedje** [comment]
Is this on my end? :

  File "ssl.py", line 1117, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Loweedje** [comment]
Nevermind it’s the mapquest certificate (again, according to thread from 2019 they forgot to renew it in time…) 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
