### ISSUE TITLE
How to correctly Import new features using the tool and open street map

### ISSUE THREAD

**Issue by Padili01** [chadrockey/TGC-Designer-Tools#40]
Hi, I forgot to include a water hazard to my course, but every time I try to do it using the course that I already edit, it revert to the original state. Can we add stuff using open street map without losing all corrections made to the course, and if it is possible can you explain how?

Thanks,

Padili01

**Comment by chadrockey** [comment]
No, I don't support things once they've touched the designer.

This tool only adds placeholder for water hazards, so you have to do them by hand in game anyway.
