### ISSUE TITLE
OSM Not Importing

### ISSUE THREAD

**Issue by BigDaddyWhite** [chadrockey/TGC-Designer-Tools#43]
I've tried following the tutorial as best I can but I can't seem to get data from OSM to populate into the 2D preview or the final course output. I only recently started mapping the course on OSM with the instructions at https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course.

Didn't know if there was a certain amount of time before the data could be pulled from OSM or if I'm missing a step? Any help would be awesome.

**Comment by BigDaddyWhite** [comment]
I looked through the text output created in the 'Import Terrain and Features' tab and it appears the longitude is off by 90. Does anybody know what might cause this and if I will need to manually override it somehow?

**Comment by chadrockey** [comment]
Sounds like the EPSG or projection is off.  Support questions should be asked here:
https://tgctours.proboards.com/board/98/lidar-help
