### ISSUE TITLE
lidar help

### ISSUE THREAD

**Issue by timothycsimons** [chadrockey/TGC-Designer-Tools#45]
I've converted the .laz files to .las, but when i use your program i get this message:

Could not find metadata for USGS_LPC_CA_LosAngeles_2016_L4_6471_1868a_LAS_2018.las.
Could not determine lidar projection, please report an issue and send this lidar and metadata
Alternatively, look for something called EPSG Value in Metadata and provide EPSG.

What does this mean, or how do i find that EPSG?

**Comment by chadrockey** [comment]
You don't need to convert laz to las (only in the rare case that you don't have enough RAM would you need to do this).

The EPSG support forum is here:
https://tgctours.proboards.com/thread/18202/help-asking-me-epsg-code
