### ISSUE TITLE
Still having problem Processing Lidar with new version 0.3.1

### ISSUE THREAD

**Issue by MJC24** [chadrockey/TGC-Designer-Tools#46]
Hey Chad.   I wasn't having any issues up until yesterday.  I saw this morning that a new version 0.3.1 was released last night, and it looks like it addresses the exact problem I started having when I try to Process Lidar.  It fails to retrieve data from prj2epsg.org API.
I tried 0.3.1 today, but I am getting the same error.  Any idea if I did something incorrectly or what else could be causing the issue?   Thanks!

![image](https://user-images.githubusercontent.com/64922522/81219125-4c462100-8fad-11ea-918f-a9931097abb8.png)

**Comment by paulrwebster** [comment]
I cannot make a flat course from an OSM file on 0.3.1, I get the message 
"Problem looking up epsg with prj2epsg.org and/or spatialreference.org, try running the tool later."
spatialrefernce.org doesn't appear to be down.

**Comment by sesurb** [comment]
I am having the the same issue. prj2epsg.org appears to be down.

**Comment by MJC24** [comment]
A friend found a workaround until the API is back up.  Open up the XML file which should have downloaded with the LiDAR data.  Look for this line in the code ("MapProjectionDefinition"):
![image](https://user-images.githubusercontent.com/64922522/81308352-ae576280-904f-11ea-8803-05232ad57a8f.png)

Scroll all the way over to the right on that line and at the end you should see ["ESPG", #####]:
![image](https://user-images.githubusercontent.com/64922522/81308641-02624700-9050-11ea-8112-178346687d0c.png)

In my case it is 3424.  Enter that number into the "Force Lidar" box on the Process Lidar tab in the TGC Tools app:
![image](https://user-images.githubusercontent.com/64922522/81308753-2b82d780-9050-11ea-8f14-13123f728419.png)

Then click the Select Lidar button and continue as you normally would.  It should generate.
