### ISSUE TITLE
Lost newbie

### ISSUE THREAD

**Issue by JohnSlicer** [chadrockey/TGC-Designer-Tools#48]
I see a lot of timeout messaging and I just don't know enough to know what I am missing or doing incorrectly? I will attach the screenshot (where I am trying to follow the Muirfield tutorial until I can get the hang of this).

![Lidat program stoppping point](https://user-images.githubusercontent.com/65207685/81633953-7e071f80-93d3-11ea-97f6-024d98aa5017.PNG)

**Comment by chadrockey** [comment]
I don't do individual support here, this is for technical issues reported by developers.
