### ISSUE TITLE
New alternate epsg code needs a few tweaks. 

### ISSUE THREAD

**Issue by RioSewell** [chadrockey/TGC-Designer-Tools#49]
I'm finding that the max retries is passing by the 404 error catch that's supposed to handle prj2epsg being down, so there needs to be another check for the timeout to also try the other website on timeout rather than just on 404. 

I also found that it automatically uses esri for the other website (https://www.spatialreference.org/ref/esri + str(epsg) + '/prj/') Which gives me a not found error because the correct link for me was https://www.spatialreference.org/ref/epsg/32717/prj/

(Perhaps because it looks for esri if 404 not found, which would make sense if prj2epsg is up), but we should also have a seperate case for the timeout that uses the above fix I suggested.

It looks like it might have to force epsg as well if the timeout error occurs. I tried it on a local source version and it seemed to work. 

Not sure if there's a way to check for this easily. I could try and find a way to fix it over the weekend but it probably won't be up to coding standards. 

Let me know what you think.

**Comment by chadrockey** [comment]
Give it a shot!  You don’t know unless you try.

**Comment by chadrockey** [comment]
Thanks for the report.

Resolved here:
https://github.com/chadrockey/TGC-Designer-Tools/commit/32c471746fa243e5ce12f8418bb2f644fce3023d
