### ISSUE TITLE
Problem looking up epsg

### ISSUE THREAD

**Issue by spc391** [chadrockey/TGC-Designer-Tools#51]
Hi there - I continue to receive the error "Problem looking up epsg with prj2epsg.org and/or spatialreference.org, try running the tool later." when running the software. Just curious if anyone knows of a work around. Not an experienced software developer. Just looking to generate a course. Pretty confident I pulled the correct .LAS and .XML files from the National Map. Followed the tutorial verbatim. 

Thanks in advance for any advice.

**Comment by Esteb22** [comment]
Did you get the issue resolved? I am having a similar problem...

**Comment by AFPA23** [comment]
I am having this same problem. EPSG lookups online do not work either.
