### ISSUE TITLE
Scalling

### ISSUE THREAD

**Issue by ifricker** [chadrockey/TGC-Designer-Tools#52]
Thank you for developing this tool.

This is my first time using it and have run into two issues.  

1. My golf edits to open street maps do not seem to show up. (not as important)
2. After going through the engine process it seems that the course is scaled incorrectly.  The entire course does not fit on the map.  I opened it the game and measured some of the noticeable elevation changes that were not cut off and they were off significantly.

**Comment by chadrockey** [comment]
You're probably using the wrong EPSG or the wrong EPSG was encoded into the data.

If you don't see 1), then 2) shouldn't work.  The reason 1 doesn't show up is because your data is being placed on the wrong part of the planet.
