### ISSUE TITLE
LAS Lidar Files not showing up

### ISSUE THREAD

**Issue by Famous58** [chadrockey/TGC-Designer-Tools#56]
I have Lidar info available on my course. I have downloaded the .zip files and extracted them several times now. None of the LAS files or metadata seem to be compatible with the tool. Or they aren't showing up at least. Is there something I can download to view or convert them to the correct file type so that I can import the data for my course? Everything else seems to be going as planned, except the lidar data. Any help would be greatly appreciated. Thanks!

**Comment by MBUA2309** [comment]
I had to download the metadata and LAZ files separately. Then I moved the laz file and the metadata to a combined folder named for the course in building. The metadata files were all the same size and my computer named them the same but they clearly contained different data.

**Comment by chadrockey** [comment]
Hi @Famous58 this doesn't seem to be an issue with the tool itself.  For user support if you're still seeing this issue, you could make a post on the TGC Tours forum:

https://tgctours.proboards.com/board/97/tgc-golf-tools-lidar-osm
