### ISSUE TITLE
Importing directly into PGA Tour 2K21

### ISSUE THREAD

**Issue by UnderDogg** [chadrockey/TGC-Designer-Tools#57]
hey @chadrockey,
The tool works flawlessly, but I (we) would be very grateful if we could import these files directly into PGA Tour 2K21.

Can you let us know when (if) you would work on that?

I'll be happy to beta-test.

**Comment by chadrockey** [comment]
I don't own a copy of 2K21 and don't plan on updating at this time.  PR are highly welcome though!

Duplicate of #55
