### ISSUE TITLE
Lidar from Government Agency, Finding EPSG

### ISSUE THREAD

**Issue by agcsu21** [chadrockey/TGC-Designer-Tools#59]
The lidar data I needed was not available through noaa website but I was able to have a GIS technician pull it for me. The link to download the file is below but I'm wondering if someone can help me decipher the metadata to find the EPSG or if I need to request XML files for each LAS file? Is there any way to get TGC Golf Tools to work with the data I received from the link below?

[Lidar](https://gisftp.colorado.gov/#/State%20Data/OIT-GIS/ColoradoData/Physical%20Geography/AustinGeuke_LiDAR/)

**Comment by chadrockey** [comment]
Hi @agcsu21 , Is the GIS technician able to tell you what projection they used?  Without them saying, it's difficult to know which of the many options could have been used and it can have subtle results on the final course.
