### ISSUE TITLE
Downloading Files from Openstreetmap & Nationalmap Lidar 

### ISSUE THREAD

**Issue by JoeyWalsh10** [chadrockey/TGC-Designer-Tools#61]
When I’m exporting and downloading the files I need my computer is asking me what app to use to download these files (for ex: internet explorer, notepad etc.) What program/app do I need to download these files to my computer correctly? 

Thanks,

Joey

**Comment by JoeyWalsh10** [comment]
I have a brand new computer. Do I need word, excel?? What program do I need to download these files correctly?

**Comment by chadrockey** [comment]
Hi @JoeyWalsh10 

Github is primarily for developer support and specific bugs.  For user assistance, the community provides support at https://tgctours.proboards.com/board/97/tgc-golf-tools-lidar-osm
