### ISSUE TITLE
OSM cartpath proposal notice

### ISSUE THREAD

**Issue by lectrician1** [chadrockey/TGC-Designer-Tools#64]
I was informed by a member of the OSM community that your plugin relies on OSM golf course data.

A proposal by me has been created about replacing the current tagging scheme for golf cartpaths from:
```
highway=service
golf=cartpath
```

to what's currently being discussed:
```
highway=cartpath
```
Here is the proposal page: https://wiki.openstreetmap.org/wiki/Proposed_features/cartpath

This is just a notice. If you have any questions or suggestions, please comment on the proposal [talk page](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/cartpath) or contact me via one of these [methods](https://wiki.openstreetmap.org/wiki/User:Lectrician1#Social_Media_.26_Contact_Info).

**Comment by chadrockey** [comment]
@lectrician1 thanks for reaching out.  I left a reply on the comments page.
