### ISSUE TITLE
Lidar data not classified

### ISSUE THREAD

**Issue by KingBoo67** [chadrockey/TGC-Designer-Tools#67]
I have a Las file of lidar points that are already filtered to ground points and would like to use it to create a course but when I try to add the file using the tool I get the error saying its not classified. Is there a way or can some one add the ground classification to all the points in the point cloud?

**Comment by chadrockey** [comment]
@KingBoo67 Sorry, I'm not familiar with tools to process/modify lidar.  Usually this also indicates the data is old and not accurate enough to build a course.  If someone made this lidar for you, could you ask them to keep the classification field?
