### ISSUE TITLE
Lidar Issue

### ISSUE THREAD

**Issue by brent628** [chadrockey/TGC-Designer-Tools#68]
Hi. I was asked to report this issue by the software. I've successfully used this software to create a course in the past.. now I am getting this issue. Thanks!

Could not determine lidar projection, please report an issue and send this lidar and metadata
Alternatively, look for something called EPSG Value in Metadata and provide EPSG.

**Comment by svtcontour** [comment]
I'm getting the exact same error.  I've done several courses in the past, this is my first one in a few months.  Downloaded the LAZ files and the corresponding XML files, can't get it to work.

**Comment by chadrockey** [comment]
Hi @brent628 @svtcontour , I recommend making a post on TGC Tours forum for EPSG issues.  There are too many for me to personally respond to these days, but many in the community are glad to help/offer suggestions.

Here is the getting started page:
https://tgctours.proboards.com/thread/18202/help-asking-me-epsg-code

And here is the "behind the scenes" on what it takes to find an EPSG when one is missing:
https://tgctours.proboards.com/thread/18332/brave-adventurers-seriously-find-epsg
