### ISSUE TITLE
LAZ file problem

### ISSUE THREAD

**Issue by kaptinenny14** [chadrockey/TGC-Designer-Tools#70]
Hi. I have a LAZ file downloaded but am unable to get it to work with the tools. I downloaded the file from here:
https://environment.data.gov.uk/DefraDataDownload/?Mode=survey
and have the a LAZ file after unzipping from a Pointcloud dataset. Screenshot attached.
![screenshot](https://user-images.githubusercontent.com/79654690/109182086-8bd03a80-7784-11eb-93c3-f07ec05f8df0.JPG)
No idea what to do next! Thankyou.

**Comment by Phenrik1** [comment]
You should always use .LAS, it comes with meta data etc.
Thats what I always use.

tor. 25. feb. 2021, 17:16 skrev kaptinenny14 <notifications@github.com>:

**Comment by nielsdrost7** [comment]
See your other issue. You need to download https://rapidlasso.com/LAStools/ and read the .laz file in that program. Then create a .las file
