### ISSUE TITLE
TGC-Designer-Tools not reading lidar files

### ISSUE THREAD

**Issue by north00001** [chadrockey/TGC-Designer-Tools#75]
Anyway I can send in the actual *.laz files for you to test with?

**Comment by north00001** [comment]
Actual error is : "Could not determine lidar projection"

**Comment by north00001** [comment]
Trying to send you the files per the text generated in your application.

" Could not determine lidar projection, please report an issue and send this lidar and metadata"

But file size is to big, 28MB, for sending through this open ticket application.

**Comment by Phenrik1** [comment]
If it can not find projection its not in the meta data. If you are able
download the *.LAS file.
If thats not an option find another reading. Different year or so

ons. 12. mai 2021, 16:23 skrev north00001 ***@***.***>:

**Comment by north00001** [comment]
Thanks, I'll look for a .las file.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by north00001** [comment]
Unzipped the .laz file to extract the .las file using LAStools's laszip.

This file was the result, USGS_LPC_CA_Central_Valley_2017_10SFG750850_LAS_2019.las.
Ran it through your application and got the following : 
Processing: USGS_LPC_CA_Central_Valley_2017_10SFG750850_LAS_2019.las
Using metadata: USGS_LPC_CA_Central_Valley_2017_10SFG750850_LAS_2019_meta.xml
Could not determine lidar projection, please report an issue and send this lidar and metadata
Alternatively, look for something called EPSG Value in Metadata and provide EPSG.

I've also tried a number of EPSG files for the central California area (Zone 3) with no success.
Zone 3 includes the area where Escalon Golf is located.

EPSG:2227: NAD83 / California zone 3 (ftUS)
EPSG:2768: NAD83(HARN) / California zone 3
EPSG:2872: NAD83(HARN) / California zone 3 (ftUS)
EPSG:3493: NAD83(NSRS2007) / California zone 3
EPSG:3494: NAD83(NSRS2007) / California zone 3 (ftUS)

Any Thoughts?

**Comment by chadrockey** [comment]
Epsg is 32630

projection is UTM Zone 30N as stated in the xml files:

  <spref>
    <horizsys>
      <planar>
        <gridsys>
          <gridsysn>Transverse_Mercator</gridsysn>
          <utm>
            <utmzone>30</utmzone>
            <transmer>
              <sfctrmer>0.9996</sfctrmer>
              <longcm>0.0</longcm>
              <latprjo>0.0</latprjo>
              <feast>500000.0</feast>
              <fnorth>0.0</fnorth>
            </transmer>
          </utm>
        </gridsys>
        <planci>
          <plance>coordinate pair</plance>
          <coordrep/>
          <plandu>N/A</plandu>
        </planci>
      </planar>
    </horizsys>
  </spref>

**Comment by Phenrik1** [comment]
Itd missing the script file

ons. 12. mai 2021, 18:25 skrev north00001 ***@***.***>:

**Comment by north00001** [comment]
Thanks for looking into this.

I did try Epsg is 32630 but that is not the area where the golf course is located, 

![EpSG 32630](https://user-images.githubusercontent.com/84052639/118283629-6b12a980-b484-11eb-815c-3cb1a10a933b.png)

This is the one I need to work , Epsg 2227
![EpSG 2227](https://user-images.githubusercontent.com/84052639/118283717-841b5a80-b484-11eb-99fb-0a3c75bf7bff.png)

Do I need to open a new ticket or can this one be reopened?

**Comment by north00001** [comment]
Let me say that I appreciate your work on this Designer Tool, I was and applications designer for 15 years though retired now for 7.
I am contemplating downloading the app from GitHub and seeing if I can resolve this myself.
I did a little python coding but my core was Java, PL/SQL.
HAve a good day

**Comment by north00001** [comment]
Gentlemen, thanks for your help.
I eventually found the site http://epsg.io/?q=california&page=9

Here I tried many EsPG files till I found EsPG 6339, which worked :)

Your application correctly displayed both images with the left one having the highlighted golf holes.

Success!

Closing ticket, lol

**Comment by Phenrik1** [comment]
Glad to hear it!

fre. 14. mai 2021, 19:06 skrev north00001 ***@***.***>:
