### ISSUE TITLE
Laz Lidar wont work in App

### ISSUE THREAD

**Issue by BadEddieKit** [chadrockey/TGC-Designer-Tools#9]
Hi Chad,

I am trying to process the lidar for a course that I am working on, however, it keeps giving me an error mesage.

Using metadata: USGS_LPC_MI_ManisteeCo_2015_192417_LAS_2017_meta.x ml
Could not determine lidar projection, please report an issue and send this lidar and metadata
Alternatively, look for something called EPSG Value in Metadata and provide EPSG and Conversion to Meters (1.0 for Meters, Approximately 0.3048 for Fee

I have attached a link for the Lidar, I would greatly appreciate you taking a look when you can.. 

https://www.amazon.com/clouddrive/sh...nBeAk0PyDTwbBh

Thank you!

**Comment by scoopjunior** [comment]
Same Issue with new laz and meta data.  Getting same error message.  attached zip of laz and meta data files.

[USGS_LPC_MI_31Co_Ogemaw_2016_687350_LAS_2019_meta.zip](https://github.com/chadrockey/TGC-Designer-Tools/files/3143984/USGS_LPC_MI_31Co_Ogemaw_2016_687350_LAS_2019_meta.zip)

BTW....awesome job on this program. This TGC stuff is fun and all thanks to you for your efforts.

**Comment by chadrockey** [comment]
Sorry I didn't have notifications on.  I think I've solved both of your issues on other forums.

If not, and for anyone else, the best place to post for this error is here:

http://tgctours.proboards.com/thread/18202/help-asking-me-epsg-code
