### ISSUE TITLE
Binary Data Import Issue?

### ISSUE THREAD

**Issue by trickybreeze** [chadrockey/TGC-Designer-Tools#98]
Im getting the following error when i try to import the course file. 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/109551184/179601196-b6fcb2c0-1412-4412-ae9f-9994312b38f2.png">

**Comment by chadrockey** [comment]
Might not be a TGC 2019 course file.

**Comment by trickybreeze** [comment]
i found a blank .course file for download online and it seems to work. Wonder what my issue was with my version.

**Comment by chadrockey** [comment]
Glad you got it going!  I’m not sure any 2019 file should work.  I’ve kept the version old because I don’t want the simulator version to become obsolete.

**Comment by trickybreeze** [comment]
Interesting. I got it to create the new .course file correctly but when placing it in the TGC2019 course folder it does not recognize it as a course when I open up the software.
