### ISSUE TITLE
Adding Tee Sets

### ISSUE THREAD

**Issue by trickybreeze** [chadrockey/TGC-Designer-Tools#99]
I have spent no less than 8 hrs trying to figure this out. What do i need to do in OpenStreetMaps to get more than one Tee Set to populate? Or is there some other way of going about this? I also tried adding tee boxes in TGC but the feature was grayed out.

Thank you for continuing to support this project, I have really enjoyed creating my first course! :-) 

Check out "Eagle Ridge #1 7.18.22"

**Comment by trickybreeze** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/109551184/179819645-c42ac2fe-4957-4dc8-9b85-837041b67680.png">

**Comment by chadrockey** [comment]
You should populate the longest tees in openstreet map.

Other teeboxes must be placed in the in game editor.

You can check the scoreboard by importing your finished course into the tool (just be sure not to overwrite it!).

**Comment by trickybreeze** [comment]
> You should populate the longest tees in openstreet map.
> 
> Other teeboxes must be placed in the in game editor.
> 
> You can check the scoreboard by importing your finished course into the tool (just be sure not to overwrite it!).

you are the man! figured out the in game editor part right after i posted that and that importing the finished course is great!
